import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import 'react-toastify/dist/ReactToastify.css'
import { ToastContainer } from 'react-toastify'
import ConfigNextUI from '@/components/NextUI/ConfigNextUI'
import { Footer, Header } from '@/components/Layout'
import AppProvider from '@/context/AppProvider'
import { cookies } from 'next/headers'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const cookieStore = cookies()
  const sessionToken = cookieStore.get('sessionToken')

  return (
    <html lang='en'>
      <body className={inter.className}>
        <ConfigNextUI>
          <AppProvider initialSessionToken={sessionToken?.value}>
            <Header />
            <div className='container'>
              {children}
            </div>
            <Footer />
          </AppProvider>
        </ConfigNextUI>
        <ToastContainer
          position='top-right'
          autoClose={3000}
          hideProgressBar={false}
          newestOnTop={false}
          closeOnClick
          rtl={false}
          pauseOnFocusLoss
          draggable
          pauseOnHover
          theme='light'
        />
      </body>
    </html>
  )
}
